hello:
  pattern: /hello/:name
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: index }

products:
  pattern: /products
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: products }

product:
  pattern: /product/:id
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: product }

route_1:
  pattern: /route1/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_1 }

#
route_2:
  pattern: /route2/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_2 }

#
route_3:
  pattern: /route3/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_3 }

#
route_4:
  pattern: /route4/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_4 }

#
route_5:
  pattern: /route5/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_5 }

#
route_6:
  pattern: /route6/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_6 }

#
route_7:
  pattern: /route7/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_7 }

#
route_8:
  pattern: /route8/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_8 }

#
route_9:
  pattern: /route9/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_9 }

#
route_10:
  pattern: /route10/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_10 }

#
route_11:
  pattern: /route11/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_11 }

#
route_12:
  pattern: /route12/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_12 }

#
route_13:
  pattern: /route13/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_13 }

#
route_14:
  pattern: /route14/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_14 }

#
route_15:
  pattern: /route15/:slug
  defaults: { _bundle: HelloBundle, _controller: Hello, _action: route_15 }
